# If you change any of these settings, website will need to be rebuilt

# Site settings
title: Wobe
email: support@wobe.co.id
description: > # this means to ignore newlines until "baseurl:"
  Ayo mulai bisnismu bersama Wobe!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wobe.co.id" # the base hostname & protocol for your site

# Wobe specific variables
play_store_url: "https://play.google.com/store/search?q=wobe"
soc_facebook: "http://facebook.com/wobe.io"
soc_instagram: "https://www.instagram.com/wobeindonesia/"

# Build settings
markdown: kramdown
