# If you change any of these settings, website will need to be rebuilt

# Site settings
title: Wobe
email: info@wobe.io
description: > # this means to ignore newlines until "baseurl:"
  Mobile & finance tool to help you kickstart your own business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wobe.io" # the base hostname & protocol for your site

# Wobe specific variables
play_store_url: "https://play.google.com/store/search?q=wobe"
soc_facebook: "http://facebook.com/wobe.io"
soc_twitter: "http://twitter.com/Wobe_ID"
soc_youtube: "https://www.youtube.com/channel/UCUHFZXe7m9RBrZ6L1SWVcrA"

# Build settings
markdown: kramdown
